# Generated by Django 5.1.3 on 2024-12-31 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.AddField(
            model_name='film',
            name='cover',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='封面链接'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='film',
            name='nationality',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='拍摄国家'),
        ),
        migrations.AlterField(
            model_name='film',
            name='types',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='年代'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
    ]
