# Generated by Django 5.1.3 on 2024-12-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_user_sex_film_cover_user_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lovedir',
            name='count',
        ),
        migrations.AddField(
            model_name='lovedir',
            name='cnt',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='包含电影个数'),
        ),
    ]
