# Generated by Django 5.1.3 on 2025-01-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_lovedir_count_lovedir_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='用户名'),
        ),
    ]
