# Generated by Django 5.1.3 on 2025-01-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='include',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='收藏时间'),
        ),
    ]
