# Generated by Django 5.1.3 on 2025-01-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_include_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='年代'),
        ),
        migrations.AlterField(
            model_name='lovedir',
            name='cnt',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='包含电影个数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
    ]
