# Generated by Django 5.1.3 on 2025-01-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_film_year_alter_lovedir_cnt_alter_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='comment',
            field=models.CharField(blank=True, default='暂无评论', max_length=256, null=True, verbose_name='评论'),
        ),
        migrations.AddField(
            model_name='film',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True, verbose_name='评分'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
