# Generated by Django 5.1.3 on 2025-01-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_film_comment_film_score_delete_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='act',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='act',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='act',
            name='film',
        ),
        migrations.AlterUniqueTogether(
            name='direct',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='direct',
            name='director',
        ),
        migrations.RemoveField(
            model_name='direct',
            name='film',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Act',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='Direct',
        ),
    ]
