# Generated by Django 5.1.3 on 2025-01-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_act_unique_together_remove_act_actor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.CharField(blank=True, default='暂无', max_length=64, null=True, verbose_name='主演列表'),
        ),
        migrations.AddField(
            model_name='film',
            name='directors',
            field=models.CharField(blank=True, default='暂无', max_length=64, null=True, verbose_name='导演列表'),
        ),
    ]
