# Generated by Django 5.1.3 on 2025-01-03 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_film_actors_film_directors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lovedir',
            name='cnt',
        ),
    ]
