# Generated by Django 5.1.3 on 2025-01-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_lovedir_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='lovedir',
            name='cnt',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='包含电影个数'),
        ),
    ]
