# Generated by Django 5.1.3 on 2025-01-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_lovedir_cnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.IntegerField(verbose_name='用户个数')),
            ],
            options={
                'db_table': 'user_cnt',
                'managed': False,
            },
        ),
    ]
