# Generated by Django 5.1.3 on 2025-01-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_film_actors_alter_film_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='actors',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='主演列表'),
        ),
        migrations.AlterField(
            model_name='film',
            name='comment',
            field=models.CharField(blank=True, default='暂无评论', max_length=512, null=True, verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='film',
            name='directors',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='导演列表'),
        ),
        migrations.AlterField(
            model_name='film',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True, verbose_name='评分'),
        ),
    ]
